# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0588578dfcc96c60ee6be8726633705ce42af8707813c4c2b46e703ff6b984aab3f0e250e5210ccfa1509c0e6749c6f855af814edbcbaad2f2f8d40b00e25163

test:
  secret_key_base: 48291772a53c7594582813af16d7db43c1653365286457f1d952e269c130883f9a436d71d8ea4ed35172cb61502e6b258ed4c0cbfc296d583fc1339de78ea3ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
